In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Persikov_binding_zf3.xlsx')

Minimal columns to include dna, f1, f2, f3

In [3]:
df['dna'].unique()

array(['ctcgcgGGGgcggcc', 'ctcgatTGGgcggcc', 'ctcgatAAAgcggcc',
       'ctcgatAACgcggcc', 'ctcgatAAGgcggcc', 'ctcgatAATgcggcc',
       'ctcgatACAgcggcc', 'ctcgatACCgcggcc', 'ctcgatACGgcggcc',
       'ctcgatACTgcggcc', 'ctcgatAGAgcggcc', 'ctcgatAGGgcggcc',
       'ctcgatATAgcggcc', 'ctcgatATGgcggcc', 'ctcgatATTgcggcc',
       'ctcgatAGTgcggcc', 'ctcgatTAGgcggcc', 'ctcgatCAAgcggcc',
       'ctcgatCCAgcggcc', 'ctcgatCGAgcggcc', 'ctcgatCTAgcggcc',
       'ctcgatCACgcggcc', 'ctcgatCCCgcggcc', 'ctcgatCGCgcggcc',
       'ctcgatCTCgcggcc', 'ctcgatCAGgcggcc', 'ctcgatCCGgcggcc',
       'ctcgatCGGgcggcc', 'ctcgatCTGgcggcc', 'ctcgatCATgcggcc',
       'ctcgatCCTgcggcc', 'ctcgatCGTgcggcc', 'ctcgatCTTgcggcc',
       'cccgcgGGGgcgtcc', 'cccgcgGGAgcgtcc', 'cccgcgGGTgcgtcc',
       'cccgcgGGCgcgtcc', 'cccgcgGAGgcgtcc', 'cccgcgGAAgcgtcc',
       'cccgcgGATgcgtcc', 'cccgcgGACgcgtcc', 'cccgcgGTGgcgtcc',
       'cccgcgGTAgcgtcc', 'cccgcgGTTgcgtcc', 'cccgcgGTCgcgtcc',
       'cccgcgGCGgcgtcc', 'cccgcgGCAgcgt

In [4]:
df.head()

Unnamed: 0   source              dna           f1           f2  \
0           0  DBSFB01  ctcgcgGGGgcggcc  KSADLKRHIRI  RSDHLTTHIRT   
1           4  DBSFB01  ctcgcgGGGgcggcc  KSADLKRHIRI  RSDHLTTHIRT   
2           5  DBSFB01  ctcgcgGGGgcggcc  KSADLKRHIRI  RSDHLTTHIRT   
3           6  DBSFB01  ctcgcgGGGgcggcc  KSADLKRHIRI  RSDHLTTHIRT   
4           7  DBSFB01  ctcgcgGGGgcggcc  KSADLKRHIRI  RSDHLTTHIRT   

            f3  ex   Kd             dna2  f4  ...  KdSd   Ka  KaSd  f12  f22  \
0  RSDERKRHTKI  Kd  0.5              NaN NaN  ...   NaN  NaN   NaN  NaN  NaN   
1  RSDERKRHTKI   >  NaN  ctcgcgGACgcggcc NaN  ...   NaN  NaN   NaN  NaN  NaN   
2  RSDERKRHTKI   >  NaN  ctcgcgGATgcggcc NaN  ...   NaN  NaN   NaN  NaN  NaN   
3  RSDERKRHTKI   >  NaN  ctcgcgGCAgcggcc NaN  ...   NaN  NaN   NaN  NaN  NaN   
4  RSDERKRHTKI   >  NaN  ctcgcgGCCgcggcc NaN  ...   NaN  NaN   NaN  NaN  NaN   

   f32   cs  lbl                                                PWM  \
0  NaN  NaN  NaN  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...   
1  NaN  NaN  NaN  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...   
2  NaN  NaN  NaN  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...   
3  NaN  NaN  NaN  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...   
4  NaN  NaN  NaN  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...   

                                                PWM2  
0                                                 []  
1  [[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...  
2  [[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...  
3  [[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]\n [1 0 1 0 1 ...  
4  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...  

[5 rows x 22 columns]

In [5]:
fingers_dictionary = sorted(df[['f1', 'f2', 'f3']].melt()['value'].str.upper().unique())

In [6]:
fingers_dictionary

['AKRMLGQ---',
 'AKRMLGQHIRT',
 'AMGHLVEHIRT',
 'AREVLQRHTR',
 'AREVLQRHTRT',
 'ARSNLLRHTR',
 'ARSNLLRHTRT',
 'ASADLTR',
 'ASADLTRHIR',
 'ASDDLTQ',
 'ASSTRTK',
 'ASWELTRHIR',
 'ATGA-HN---',
 'CCAHLSEHIRT',
 'CPSNLRRHGRT',
 'CSDHLTTHIR',
 'DASARKRHTK',
 'DASTRKRHTK',
 'DCRDLAR---',
 'DCRDLARHIRT',
 'DHANLARHTR',
 'DHANLARHTRT',
 'DHQDLTIHIRT',
 'DHSSRKRHTK',
 'DKKDLTRHIRT',
 'DLRSCRSHIRT',
 'DLRWLVVHIRT',
 'DPGALVR---',
 'DPGALVRHIRT',
 'DPGDLVRHIRT',
 'DPGELVRHIRT',
 'DPGHLARHIRT',
 'DPGHLVRHIRT',
 'DPGKLARHIRT',
 'DPGNLKR---',
 'DPGNLKRHIRT',
 'DPGNLVRHIRT',
 'DPHNRKRHTK',
 'DRANLST',
 'DRANRKRHTK',
 'DRKVLATHIRT',
 'DRRLLDRHQR',
 'DRRLLDRHQRT',
 'DRSALARAHLRW',
 'DRSALARDHLSK',
 'DRSALARRHKRT',
 'DRSDLTRDHLSK',
 'DRSDLTRRHKRT',
 'DRSHLARDHLSK',
 'DRSHLARRHKRT',
 'DRSHLTRAHLRW',
 'DRSKLARHIRT',
 'DRSNLERHTR',
 'DRSNLERHTRT',
 'DRSNLTRAHLRW',
 'DRSNLTRDHLSK',
 'DRSNLTRRHKRT',
 'DRSSLTRHTR',
 'DRSSLTRHTRT',
 'DSAHLTR',
 'DSANLTRHIR',
 'DSANRTK',
 'DSGNLRVHIRT',
 'DSKDLTRHIR',
 'DSRARKRH

In [7]:
dna_dictionary = df['dna'].str.upper().unique()

In [8]:
dna_dictionary

array(['CTCGCGGGGGCGGCC', 'CTCGATTGGGCGGCC', 'CTCGATAAAGCGGCC',
       'CTCGATAACGCGGCC', 'CTCGATAAGGCGGCC', 'CTCGATAATGCGGCC',
       'CTCGATACAGCGGCC', 'CTCGATACCGCGGCC', 'CTCGATACGGCGGCC',
       'CTCGATACTGCGGCC', 'CTCGATAGAGCGGCC', 'CTCGATAGGGCGGCC',
       'CTCGATATAGCGGCC', 'CTCGATATGGCGGCC', 'CTCGATATTGCGGCC',
       'CTCGATAGTGCGGCC', 'CTCGATTAGGCGGCC', 'CTCGATCAAGCGGCC',
       'CTCGATCCAGCGGCC', 'CTCGATCGAGCGGCC', 'CTCGATCTAGCGGCC',
       'CTCGATCACGCGGCC', 'CTCGATCCCGCGGCC', 'CTCGATCGCGCGGCC',
       'CTCGATCTCGCGGCC', 'CTCGATCAGGCGGCC', 'CTCGATCCGGCGGCC',
       'CTCGATCGGGCGGCC', 'CTCGATCTGGCGGCC', 'CTCGATCATGCGGCC',
       'CTCGATCCTGCGGCC', 'CTCGATCGTGCGGCC', 'CTCGATCTTGCGGCC',
       'CCCGCGGGGGCGTCC', 'CCCGCGGGAGCGTCC', 'CCCGCGGGTGCGTCC',
       'CCCGCGGGCGCGTCC', 'CCCGCGGAGGCGTCC', 'CCCGCGGAAGCGTCC',
       'CCCGCGGATGCGTCC', 'CCCGCGGACGCGTCC', 'CCCGCGGTGGCGTCC',
       'CCCGCGGTAGCGTCC', 'CCCGCGGTTGCGTCC', 'CCCGCGGTCGCGTCC',
       'CCCGCGGCGGCGTCC', 'CCCGCGGCAGCGT

In [9]:
dna_data = df['dna'].str.upper().map(lambda x: list(dna_dictionary).index(x))

In [10]:
finger_data = np.array([df['f1'].str.upper().map(lambda x: list(fingers_dictionary).index(x)).values, 
 df['f2'].str.upper().map(lambda x: list(fingers_dictionary).index(x)).values,
 df['f3'].str.upper().map(lambda x: list(fingers_dictionary).index(x)).values])

In [11]:
dna_data.shape

(3099,)

In [12]:
finger_data.shape

(3, 3099)

In [13]:
dna_data[0:5]

0    0
1    0
2    0
3    0
4    0
Name: dna, dtype: int64

In [14]:
pd.DataFrame(dna_data).median()

dna    110.0
dtype: float64

In [15]:
finger_data[:, dna_data == 0]

array([[179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179],
       [689, 689, 689, 689, 689, 689, 689, 689, 689, 689, 689, 689],
       [653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653]])

In [16]:
np.unique(finger_data[:, dna_data == 34])

array([179, 273, 366, 417, 454, 653])

In [17]:
pd.Series(finger_data[:, dna_data == 34].ravel()).value_counts()

179    49
653    49
454    23
366    19
417     6
273     1
dtype: int64

In [18]:
finger_data[:, dna_data == 34]

array([[179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179],
       [366, 273, 366, 366, 366, 366, 366, 366, 366, 366, 366, 366, 454,
        417, 366, 454, 366, 366, 366, 454, 454, 454, 454, 454, 454, 454,
        454, 454, 454, 417, 417, 417, 417, 417, 366, 366, 366, 366, 454,
        454, 454, 454, 454, 454, 454, 454, 454, 454, 454],
       [653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653,
        653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653,
        653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653,
        653, 653, 653, 653, 653, 653, 653, 653, 653, 653]])

In [19]:
finger_data[:, dna_data == 35]

array([[179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179],
       [806, 828, 854, 898, 928, 926, 877, 880, 900, 902, 806, 806, 806,
        806, 806, 806, 806, 884, 884, 884, 884, 884, 884, 884, 884, 884,
        884, 884, 884, 884, 884, 884, 884, 884, 900, 902, 870, 884, 804,
        884, 884, 884, 884, 884, 884, 900, 900, 900, 900, 900, 900, 900,
        902, 902, 902, 902, 902, 870, 870, 870, 870, 870, 870, 870, 884,
        884, 884, 884, 884, 804, 804, 804, 804, 804, 804, 804, 804, 804],
       [653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653,
        653, 653, 653, 653, 653, 653, 653, 653, 6

In [20]:
list(df['dna'].loc[dna_data[dna_data == 35].index].unique())

['cccgcgGGTgcgtcc']

In [21]:
list(df['dna'].loc[dna_data[dna_data == 34].index].unique())

['cccgcgGGAgcgtcc']

In [22]:
finger_data[:, dna_data == 36]

array([[179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179],
       [ 98,  98,  98,  98,  98,  98,  98,  98,  98,  98,  98,  32,  32,
         32,  32,  32,  32,  32,  32,  32,  32,  32,  32, 884,  32, 192,
         32,  98,  51,  33,  31, 367, 457, 886, 192, 192,  32,  32,  32,
         32,  32,  32,  32,  32,  32,  98,  98,  98,  51,  51,  51,  51,
         51,  51,  51,  51,  51,  33,  33,  33,  33,  33,  33,  31,  31,
         31,  31,  31,  31,  31,  31,  31,  31, 367, 367, 367, 367, 457,
        457, 457, 457, 457, 886],
       [653, 653, 653, 653, 653, 653, 653, 653, 653, 653

In [23]:
list(df['dna'].loc[dna_data[dna_data == 36].index].unique())

['cccgcgGGCgcgtcc']

In [24]:
list(df['dna'].loc[dna_data[dna_data == 37].index].unique())

['cccgcgGAGgcgtcc']

In [25]:
finger_data[:, dna_data == 37]

array([[179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179],
       [706, 595, 522, 543, 628, 706, 706, 706, 706, 706, 706, 706, 706,
        706, 706, 706, 706, 706, 706, 711, 711, 711, 711, 711, 711, 711,
        711, 711, 647, 628, 706, 711, 620, 628, 716, 724, 615, 187, 190,
        191, 646, 613, 706, 706, 706, 706, 706, 706, 706, 706, 706, 706,
        706, 711, 711, 620, 620, 628, 716, 716, 716, 716, 724, 724, 724,
        724, 187, 187, 190, 190, 190, 190, 646, 646, 646, 646, 613, 613,
        613, 613, 613, 613, 613, 613, 613],
       [653, 653, 653, 653, 653, 653

In [26]:
list(df['dna2'].loc[dna_data[dna_data == 37].index].unique())

[nan,
 'cccgcgGGGgcgtcc',
 'cccgcgGGAgcgtcc',
 'cccgcgGGTgcgtcc',
 'cccgcgGGCgcgtcc',
 'cccgcgGAAgcgtcc',
 'cccgcgGATgcgtcc',
 'cccgcgGACgcgtcc',
 'cccgcgGTGgcgtcc',
 'cccgcgGTAgcgtcc',
 'cccgcgGTTgcgtcc',
 'cccgcgGTCgcgtcc',
 'cccgcgGCGgcgtcc',
 'cccgcgGCAgcgtcc',
 'cccgcgGCCgcgtcc',
 'cccgcgGCTgcgtcc']

In [27]:
list(df['dna'].loc[dna_data[dna_data == 37].index].unique())

['cccgcgGAGgcgtcc']

+ Look at f2 when dna > dna2: is it consistent 
+ Does the variation in f2 come from dna2 > dna - NO

In [28]:
finger_data[1, dna_data == 37]

array([706, 595, 522, 543, 628, 706, 706, 706, 706, 706, 706, 706, 706,
       706, 706, 706, 706, 706, 706, 711, 711, 711, 711, 711, 711, 711,
       711, 711, 647, 628, 706, 711, 620, 628, 716, 724, 615, 187, 190,
       191, 646, 613, 706, 706, 706, 706, 706, 706, 706, 706, 706, 706,
       706, 711, 711, 620, 620, 628, 716, 716, 716, 716, 724, 724, 724,
       724, 187, 187, 190, 190, 190, 190, 646, 646, 646, 646, 613, 613,
       613, 613, 613, 613, 613, 613, 613])

# Plan

1. Fields:
* Input = 'dna'
* Output = 'f1', 'f2', 'f3'

2. Transforms
* Dictionary for 'dna' and for 'f' fields

3. LSTM text generation (https://machinelearningmastery.com/text-generation-lstm-recurrent-neural-networks-python-keras/)


# Step 1: Get input and output fields

In [29]:
dna_data.values.shape

(3099,)

In [30]:
finger_data.shape

(3, 3099)

# Step 2: Pandas to the rescue

Pandas already has the one hot encoding for column

In [31]:
fingers_onehot = pd.get_dummies(df, columns=['f1', 'f2', 'f3'])

In [32]:
fingers_onehot.filter(like='f1_').values.shape

(3099, 180)

In [33]:
dna_onehot = pd.get_dummies(df, columns=['dna'])

In [34]:
dna_onehot.shape

(3099, 504)

In [35]:
dna_onehot

Unnamed: 0   source           f1           f2           f3  ex     Kd  \
0              0  DBSFB01  KSADLKRHIRI  RSDHLTTHIRT  RSDERKRHTKI  Kd    0.5   
1              4  DBSFB01  KSADLKRHIRI  RSDHLTTHIRT  RSDERKRHTKI   >    NaN   
2              5  DBSFB01  KSADLKRHIRI  RSDHLTTHIRT  RSDERKRHTKI   >    NaN   
3              6  DBSFB01  KSADLKRHIRI  RSDHLTTHIRT  RSDERKRHTKI   >    NaN   
4              7  DBSFB01  KSADLKRHIRI  RSDHLTTHIRT  RSDERKRHTKI   >    NaN   
...          ...      ...          ...          ...          ...  ..    ...   
3094        4078    WYB95  RSDELTRHIRI  RTGNYTTHIRT  RSDERKRHTKI  Kd   20.0   
3095        4079    WYB95  RSDELTRHIRI  RSDHLTTHIRT  RSDERKRHTKI  Kd    6.5   
3096        4080    WYB95  RSDELTRHIRI  RSDHLTTHIRT  RSDERKRHTKI  Kd  101.0   
3097        4081    WYB95  RSDELTRHIRI  RSDHLTTHIRT  SSGQWWRHTKI  Kd   13.1   
3098        4082    WYB95  RSDELTRHIRI  RSDHLTTHIRT  SSGQWWRHTKI  Kd  500.0   

                 dna2  f4  f5  ...  dna_tctGCCtgggcggaa  dna_tctGCGtgggcggaa  \
0                 NaN NaN NaN  ...                    0                    0   
1     ctcgcgGACgcggcc NaN NaN  ...                    0                    0   
2     ctcgcgGATgcggcc NaN NaN  ...                    0                    0   
3     ctcgcgGCAgcggcc NaN NaN  ...                    0                    0   
4     ctcgcgGCCgcggcc NaN NaN  ...                    0                    0   
...               ...  ..  ..  ...                  ...                  ...   
3094              NaN NaN NaN  ...                    0                    0   
3095              NaN NaN NaN  ...                    0                    0   
3096              NaN NaN NaN  ...                    0                    0   
3097              NaN NaN NaN  ...                    0                    0   
3098              NaN NaN NaN  ...                    0                    0   

     dna_tctGCTtgggcggaa  dna_tctGGAtgggcggaa dna_tctGGGtgggcggaa  \
0                      0                    0                   0   
1                      0                    0                   0   
2                      0                    0                   0   
3                      0                    0                   0   
4                      0                    0                   0   
...                  ...                  ...                 ...   
3094                   0                    0                   0   
3095                   0                    0                   0   
3096                   0                    0                   0   
3097                   0                    0                   0   
3098                   0                    0                   0   

     dna_tctGGTtgggcggaa dna_tctGTAtgggcggaa dna_tctGTCtgggcggaa  \
0                      0                   0                   0   
1                      0                   0                   0   
2                      0                   0                   0   
3                      0                   0                   0   
4                      0                   0                   0   
...                  ...                 ...                 ...   
3094                   0                   0                   0   
3095                   0                   0                   0   
3096                   0                   0                   0   
3097                   0                   0                   0   
3098                   0                   0                   0   

     dna_tctGTGtgggcggaa dna_tctGTTtgggcggaa  
0                      0                   0  
1                      0                   0  
2                      0                   0  
3                      0                   0  
4                      0                   0  
...                  ...                 ...  
3094                   0                   0  
3095                   0                   0  
3096                   0   

# Step 3: Proof of concept model

Define a 

In [36]:
import tensorflow.keras as K

In [37]:
dna_onehot

Unnamed: 0   source           f1           f2           f3  ex     Kd  \
0              0  DBSFB01  KSADLKRHIRI  RSDHLTTHIRT  RSDERKRHTKI  Kd    0.5   
1              4  DBSFB01  KSADLKRHIRI  RSDHLTTHIRT  RSDERKRHTKI   >    NaN   
2              5  DBSFB01  KSADLKRHIRI  RSDHLTTHIRT  RSDERKRHTKI   >    NaN   
3              6  DBSFB01  KSADLKRHIRI  RSDHLTTHIRT  RSDERKRHTKI   >    NaN   
4              7  DBSFB01  KSADLKRHIRI  RSDHLTTHIRT  RSDERKRHTKI   >    NaN   
...          ...      ...          ...          ...          ...  ..    ...   
3094        4078    WYB95  RSDELTRHIRI  RTGNYTTHIRT  RSDERKRHTKI  Kd   20.0   
3095        4079    WYB95  RSDELTRHIRI  RSDHLTTHIRT  RSDERKRHTKI  Kd    6.5   
3096        4080    WYB95  RSDELTRHIRI  RSDHLTTHIRT  RSDERKRHTKI  Kd  101.0   
3097        4081    WYB95  RSDELTRHIRI  RSDHLTTHIRT  SSGQWWRHTKI  Kd   13.1   
3098        4082    WYB95  RSDELTRHIRI  RSDHLTTHIRT  SSGQWWRHTKI  Kd  500.0   

                 dna2  f4  f5  ...  dna_tctGCCtgggcggaa  dna_tctGCGtgggcggaa  \
0                 NaN NaN NaN  ...                    0                    0   
1     ctcgcgGACgcggcc NaN NaN  ...                    0                    0   
2     ctcgcgGATgcggcc NaN NaN  ...                    0                    0   
3     ctcgcgGCAgcggcc NaN NaN  ...                    0                    0   
4     ctcgcgGCCgcggcc NaN NaN  ...                    0                    0   
...               ...  ..  ..  ...                  ...                  ...   
3094              NaN NaN NaN  ...                    0                    0   
3095              NaN NaN NaN  ...                    0                    0   
3096              NaN NaN NaN  ...                    0                    0   
3097              NaN NaN NaN  ...                    0                    0   
3098              NaN NaN NaN  ...                    0                    0   

     dna_tctGCTtgggcggaa  dna_tctGGAtgggcggaa dna_tctGGGtgggcggaa  \
0                      0                    0                   0   
1                      0                    0                   0   
2                      0                    0                   0   
3                      0                    0                   0   
4                      0                    0                   0   
...                  ...                  ...                 ...   
3094                   0                    0                   0   
3095                   0                    0                   0   
3096                   0                    0                   0   
3097                   0                    0                   0   
3098                   0                    0                   0   

     dna_tctGGTtgggcggaa dna_tctGTAtgggcggaa dna_tctGTCtgggcggaa  \
0                      0                   0                   0   
1                      0                   0                   0   
2                      0                   0                   0   
3                      0                   0                   0   
4                      0                   0                   0   
...                  ...                 ...                 ...   
3094                   0                   0                   0   
3095                   0                   0                   0   
3096                   0                   0                   0   
3097                   0                   0                   0   
3098                   0                   0                   0   

     dna_tctGTGtgggcggaa dna_tctGTTtgggcggaa  
0                      0                   0  
1                      0                   0  
2                      0                   0  
3                      0                   0  
4                      0                   0  
...                  ...                 ...  
3094                   0                   0  
3095                   0                   0  
3096                   0   

In [38]:
dna_inputs = dna_onehot.filter(like='dna_').values
f1_outputs = fingers_onehot.filter(like='f1_').values
f2_outputs = fingers_onehot.filter(like='f2_').values
f3_outputs = fingers_onehot.filter(like='f3_').values

In [39]:
dna_inputs.shape

(3099, 483)

In [40]:
f1_outputs.shape

(3099, 180)

In [41]:
dna_inputs.shape[1]

483

In [42]:
dna_inputs.shape

(3099, 483)

In [44]:
from sklearn.model_selection import train_test_split


X_train, X_test, _, _ = train_test_split(
    dna_inputs, dna_inputs, test_size=0.33, random_state=42)


In [221]:
latent_dim = 128

class Autoencoder(K.models.Model):
  def __init__(self, latent_dim):
    super(Autoencoder, self).__init__()
    self.latent_dim = latent_dim   
    self.encoder = K.Sequential([
        K.layers.Dense(400, activation='relu'),
        K.layers.Dropout(0.3),
        K.layers.Dense(256, activation='relu'),
        K.layers.Dense(self.latent_dim, activation='relu'),
    ], name="encoder")
    self.decoder = K.Sequential([
        K.layers.Dense(256, activation='relu'),
        K.layers.Dropout(0.3),
        K.layers.Dense(400, activation='relu'),
        K.layers.Dropout(0.3),
        K.layers.Dense(dna_inputs.shape[1], activation="softmax"),
    ], name="decoder")

  def call(self, x):
    encoded = self.encoder(x)
    decoded = self.decoder(encoded)
    return decoded

autoencoder = Autoencoder(latent_dim)

In [222]:
opt = K.optimizers.Adam(lr=7e-5)

In [223]:
autoencoder.compile(loss='categorical_crossentropy', optimizer=opt)

In [224]:
data = np.expand_dims(dna_inputs.astype('float32'),1)

autoencoder.fit(X_train, X_train, epochs=100, validation_data=(X_test, X_test))

Epoch 1/100
65/65 [==============================] - 2s 24ms/step - loss: 6.1769 - val_loss: 6.1629
Epoch 2/100
65/65 [==============================] - 2s 27ms/step - loss: 6.1479 - val_loss: 6.0729
Epoch 3/100
65/65 [==============================] - 1s 22ms/step - loss: 5.9384 - val_loss: 5.4716
Epoch 4/100
65/65 [==============================] - 2s 36ms/step - loss: 5.3655 - val_loss: 5.3455
Epoch 5/100
65/65 [==============================] - 3s 43ms/step - loss: 5.1708 - val_loss: 5.2521
Epoch 6/100
65/65 [==============================] - 3s 41ms/step - loss: 5.0690 - val_loss: 5.1304
Epoch 7/100
65/65 [==============================] - 2s 37ms/step - loss: 4.9996 - val_loss: 4.9732
Epoch 8/100
65/65 [==============================] - 3s 46ms/step - loss: 4.7823 - val_loss: 4.7939
Epoch 9/100
65/65 [==============================] - 4s 65ms/step - loss: 4.6518 - val_loss: 4.6157
Epoch 10/100
65/65 [==============================] - 2s 36ms/step - loss: 4.5064 - val_loss: 4.4538

65/65 [==============================] - 3s 47ms/step - loss: 0.4593 - val_loss: 2.5160
Epoch 83/100
65/65 [==============================] - 4s 55ms/step - loss: 0.4306 - val_loss: 2.5183
Epoch 84/100
65/65 [==============================] - 3s 40ms/step - loss: 0.4387 - val_loss: 2.5370
Epoch 85/100
65/65 [==============================] - 4s 54ms/step - loss: 0.4229 - val_loss: 2.5014
Epoch 86/100
65/65 [==============================] - 3s 44ms/step - loss: 0.4314 - val_loss: 2.5798
Epoch 87/100
65/65 [==============================] - 4s 67ms/step - loss: 0.3981 - val_loss: 2.5411
Epoch 88/100
65/65 [==============================] - 3s 38ms/step - loss: 0.3544 - val_loss: 2.5640
Epoch 89/100
65/65 [==============================] - 3s 53ms/step - loss: 0.3709 - val_loss: 2.5490
Epoch 90/100
65/65 [==============================] - 2s 35ms/step - loss: 0.3803 - val_loss: 2.5372
Epoch 91/100
65/65 [==============================] - 2s 32ms/step - loss: 0.4087 - val_loss: 2.5874
Epo

In [225]:
n=4

In [226]:
autoencoder.predict(X_test[[n],:]).argmax()

300

In [227]:
np.argmax(X_test[n,:])

300

In [228]:
d = (autoencoder.predict(X_test)).argmax(axis=1)

In [229]:
e = X_test.argmax(axis=1)

In [230]:
d[40:60]

array([118, 451, 339, 232, 115, 324, 231, 121, 451, 381, 307, 348, 405,
       321,  53, 341, 310, 349, 247, 308])

In [231]:
e[40:60]

array([118, 451, 339, 232, 138, 324, 231, 121, 451, 381, 307, 348, 405,
       119,  53, 341, 310, 349, 247, 308])

In [232]:
a=0
for idx in range(len(d)):
    if d[idx] == e[idx]:
        a += 1 / len(d)
        

In [233]:
a

0.9237536656891489

In [235]:
autoencoder.summary()

Model: "autoencoder_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
encoder (Sequential)         (None, 128)               329152    
_________________________________________________________________
decoder (Sequential)         (None, 483)               329507    
Total params: 658,659
Trainable params: 658,659
Non-trainable params: 0
_________________________________________________________________


In [236]:
autoencoder.encoder.summary()

Model: "encoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_79 (Dense)             (None, 400)               193600    
_________________________________________________________________
dropout (Dropout)            (None, 400)               0         
_________________________________________________________________
dense_80 (Dense)             (None, 256)               102656    
_________________________________________________________________
dense_81 (Dense)             (None, 128)               32896     
Total params: 329,152
Trainable params: 329,152
Non-trainable params: 0
_________________________________________________________________


In [248]:
encoded_dna = autoencoder.encoder(dna_inputs).numpy()

In [249]:
encoded_dna.shape

(3099, 128)

## 10/27/2021
* Try to adjust bottleneck down to 64 or 32
* Test accuracy of model prediction on test data
* Cut encoder off to use for determining latent space
* Do same for zinc fingers
* feed into LSTM

In [255]:
inputs = K.layers.Input(shape=(1, encoded_dna.shape[1]), name="dna")
#lstm1 = K.layers.LSTM(128)(inputs)
dense1 = K.layers.Dense(1024)(inputs)
dense2 = K.layers.Dense(f1_outputs.shape[1])(dense1)

model = K.models.Model(inputs=[inputs], outputs=[dense2])

model.summary()

Model: "model_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dna (InputLayer)             [(None, 1, 128)]          0         
_________________________________________________________________
dense_89 (Dense)             (None, 1, 1024)           132096    
_________________________________________________________________
dense_90 (Dense)             (None, 1, 180)            184500    
Total params: 316,596
Trainable params: 316,596
Non-trainable params: 0
_________________________________________________________________


# Model

Takes input one-hot by dictionary of dna domains and predicts the other dictionary of proteins (zinc fingers)

In [256]:
opt = K.optimizers.Adam(lr=1e-6)

In [257]:
model.compile(loss='categorical_crossentropy', optimizer=opt)

In [258]:
f1_outputs.shape

(3099, 180)

In [259]:
model.fit(np.expand_dims(encoded_dna.astype('float32'),1),np.expand_dims(f1_outputs.astype('float32'),1), epochs=20)

Epoch 1/20
97/97 [==============================] - 4s 36ms/step - loss: 12.6376
Epoch 2/20
97/97 [==============================] - 4s 42ms/step - loss: 10.3984
Epoch 3/20
97/97 [==============================] - 4s 45ms/step - loss: 9.5043
Epoch 4/20
97/97 [==============================] - 4s 45ms/step - loss: 9.7737
Epoch 5/20
97/97 [==============================] - 4s 38ms/step - loss: 9.4839
Epoch 6/20
97/97 [==============================] - 5s 46ms/step - loss: 9.2016
Epoch 7/20
97/97 [==============================] - 4s 46ms/step - loss: 9.1035
Epoch 8/20
97/97 [==============================] - 3s 30ms/step - loss: 9.3093
Epoch 9/20
97/97 [==============================] - 3s 34ms/step - loss: 8.4961
Epoch 10/20
97/97 [==============================] - 4s 45ms/step - loss: 8.6891
Epoch 11/20
97/97 [==============================] - 3s 30ms/step - loss: 8.5902
Epoch 12/20
97/97 [==============================] - 4s 43ms/step - loss: 8.2942
Epoch 13/20
97/97 [================

## 11/3/2021 Next time
* Do autoencoder on output too
* Try more complex model (LSTM?)
* Variable learning rate (learning rate scheduler)
* 

In [104]:
pwm = np.array([[-5.7, -3.2, 3.7, -3.2, 3.7, 0.6],
               [0.5, -3.2, -3.2, -3.2, -3.2, -5.7],
               [0.5, 3.7, -3.2, -3.2, -3.2, -5.7],
               [-5.7, -3.2, -3.2, 3.7, -3.2, 0.5]])

In [105]:
pwm

array([[-5.7, -3.2,  3.7, -3.2,  3.7,  0.6],
       [ 0.5, -3.2, -3.2, -3.2, -3.2, -5.7],
       [ 0.5,  3.7, -3.2, -3.2, -3.2, -5.7],
       [-5.7, -3.2, -3.2,  3.7, -3.2,  0.5]])

In [177]:
seq = np.array([[0,0,1,0],
              [0,1,0,0],
              [1,0,0,0],
              [0,0,0,1],
              [0,0,0,1],
              [1,0,0,0],
              [0,1,0,0],
              [0,1,0,0],
              [0,0,1,0],
              [1,0,0,0],
              [0,0,0,1],
              [1,0,0,0],
              [1,0,0,0]])

In [178]:
seq = seq.T

In [179]:
pwm.shape

(4, 6)

In [180]:
seq.shape

(4, 13)

In [195]:
np.sum(np.matmul(seq.T, pwm).T, axis=0)

array([-11.1, -18. ,  -4.1, -11.1, -11.1,  -4.1, -18. , -18. , -11.1,
        -4.1, -11.1,  -4.1,  -4.1])

In [144]:
seq[0,:]

array([0, 0, 1, 0])

In [143]:
pwm[:,0]

array([-5.7,  0.5,  0.5, -5.7])

In [146]:
np.matmul(seq[0,:], pwm[:,0])

0.5

In [147]:
np.matmul(seq[1,:], pwm[:,1])

-3.2

In [148]:
np.matmul(seq[2,:], pwm[:,2])

3.7

In [149]:
np.matmul(seq[3,:], pwm[:,3])

3.7

In [150]:
np.matmul(seq[4,:], pwm[:,4])

-3.2

In [151]:
np.matmul(seq[5,:], pwm[:,5])

0.6

In [152]:
np.matmul(seq, pwm)

array([[ 0.5,  3.7, -3.2, -3.2, -3.2, -5.7],
       [ 0.5, -3.2, -3.2, -3.2, -3.2, -5.7],
       [-5.7, -3.2,  3.7, -3.2,  3.7,  0.6],
       [-5.7, -3.2, -3.2,  3.7, -3.2,  0.5],
       [-5.7, -3.2, -3.2,  3.7, -3.2,  0.5],
       [-5.7, -3.2,  3.7, -3.2,  3.7,  0.6],
       [ 0.5, -3.2, -3.2, -3.2, -3.2, -5.7],
       [ 0.5, -3.2, -3.2, -3.2, -3.2, -5.7],
       [ 0.5,  3.7, -3.2, -3.2, -3.2, -5.7],
       [-5.7, -3.2,  3.7, -3.2,  3.7,  0.6],
       [-5.7, -3.2, -3.2,  3.7, -3.2,  0.5],
       [-5.7, -3.2,  3.7, -3.2,  3.7,  0.6],
       [-5.7, -3.2,  3.7, -3.2,  3.7,  0.6]])

In [162]:
np.diag(np.matmul(seq, pwm))

array([ 0.5, -3.2,  3.7,  3.7, -3.2,  0.6])

In [171]:
np.diag(np.matmul(seq[1:], pwm))

array([ 0.5, -3.2, -3.2,  3.7,  3.7, -5.7])

In [166]:
seq.shape

(13, 4)

In [167]:
pwm.shape

(4, 6)

In [ ]:
1x6
13x4
4x6

In [175]:
np.matmul(seq, pwm)

array([[ 0.5,  3.7, -3.2, -3.2, -3.2, -5.7],
       [ 0.5, -3.2, -3.2, -3.2, -3.2, -5.7],
       [-5.7, -3.2,  3.7, -3.2,  3.7,  0.6],
       [-5.7, -3.2, -3.2,  3.7, -3.2,  0.5],
       [-5.7, -3.2, -3.2,  3.7, -3.2,  0.5],
       [-5.7, -3.2,  3.7, -3.2,  3.7,  0.6],
       [ 0.5, -3.2, -3.2, -3.2, -3.2, -5.7],
       [ 0.5, -3.2, -3.2, -3.2, -3.2, -5.7],
       [ 0.5,  3.7, -3.2, -3.2, -3.2, -5.7],
       [-5.7, -3.2,  3.7, -3.2,  3.7,  0.6],
       [-5.7, -3.2, -3.2,  3.7, -3.2,  0.5],
       [-5.7, -3.2,  3.7, -3.2,  3.7,  0.6],
       [-5.7, -3.2,  3.7, -3.2,  3.7,  0.6]])

In [ ]:
# https://davetang.org/muse/2013/10/01/position-weight-matrix/
# https://en.wikipedia.org/wiki/Zinc_finger#/media/File:Zinc_finger_rendered.png
# https://en.wikipedia.org/wiki/Zinc_finger_nuclease
