In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Persikov_binding_zf3.xlsx')

Minimal columns to include dna, f1, f2, f3

In [52]:
df['dna'].unique()

array(['ctcgcgGGGgcggcc', 'ctcgatTGGgcggcc', 'ctcgatAAAgcggcc',
       'ctcgatAACgcggcc', 'ctcgatAAGgcggcc', 'ctcgatAATgcggcc',
       'ctcgatACAgcggcc', 'ctcgatACCgcggcc', 'ctcgatACGgcggcc',
       'ctcgatACTgcggcc', 'ctcgatAGAgcggcc', 'ctcgatAGGgcggcc',
       'ctcgatATAgcggcc', 'ctcgatATGgcggcc', 'ctcgatATTgcggcc',
       'ctcgatAGTgcggcc', 'ctcgatTAGgcggcc', 'ctcgatCAAgcggcc',
       'ctcgatCCAgcggcc', 'ctcgatCGAgcggcc', 'ctcgatCTAgcggcc',
       'ctcgatCACgcggcc', 'ctcgatCCCgcggcc', 'ctcgatCGCgcggcc',
       'ctcgatCTCgcggcc', 'ctcgatCAGgcggcc', 'ctcgatCCGgcggcc',
       'ctcgatCGGgcggcc', 'ctcgatCTGgcggcc', 'ctcgatCATgcggcc',
       'ctcgatCCTgcggcc', 'ctcgatCGTgcggcc', 'ctcgatCTTgcggcc',
       'cccgcgGGGgcgtcc', 'cccgcgGGAgcgtcc', 'cccgcgGGTgcgtcc',
       'cccgcgGGCgcgtcc', 'cccgcgGAGgcgtcc', 'cccgcgGAAgcgtcc',
       'cccgcgGATgcgtcc', 'cccgcgGACgcgtcc', 'cccgcgGTGgcgtcc',
       'cccgcgGTAgcgtcc', 'cccgcgGTTgcgtcc', 'cccgcgGTCgcgtcc',
       'cccgcgGCGgcgtcc', 'cccgcgGCAgcgt

In [3]:
df.head()

Unnamed: 0   source              dna           f1           f2  \
0           0  DBSFB01  ctcgcgGGGgcggcc  KSADLKRHIRI  RSDHLTTHIRT   
1           4  DBSFB01  ctcgcgGGGgcggcc  KSADLKRHIRI  RSDHLTTHIRT   
2           5  DBSFB01  ctcgcgGGGgcggcc  KSADLKRHIRI  RSDHLTTHIRT   
3           6  DBSFB01  ctcgcgGGGgcggcc  KSADLKRHIRI  RSDHLTTHIRT   
4           7  DBSFB01  ctcgcgGGGgcggcc  KSADLKRHIRI  RSDHLTTHIRT   

            f3  ex   Kd             dna2  f4  ...  KdSd   Ka  KaSd  f12  f22  \
0  RSDERKRHTKI  Kd  0.5              NaN NaN  ...   NaN  NaN   NaN  NaN  NaN   
1  RSDERKRHTKI   >  NaN  ctcgcgGACgcggcc NaN  ...   NaN  NaN   NaN  NaN  NaN   
2  RSDERKRHTKI   >  NaN  ctcgcgGATgcggcc NaN  ...   NaN  NaN   NaN  NaN  NaN   
3  RSDERKRHTKI   >  NaN  ctcgcgGCAgcggcc NaN  ...   NaN  NaN   NaN  NaN  NaN   
4  RSDERKRHTKI   >  NaN  ctcgcgGCCgcggcc NaN  ...   NaN  NaN   NaN  NaN  NaN   

   f32   cs  lbl                                                PWM  \
0  NaN  NaN  NaN  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...   
1  NaN  NaN  NaN  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...   
2  NaN  NaN  NaN  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...   
3  NaN  NaN  NaN  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...   
4  NaN  NaN  NaN  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...   

                                                PWM2  
0                                                 []  
1  [[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...  
2  [[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...  
3  [[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]\n [1 0 1 0 1 ...  
4  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n [1 0 1 0 1 ...  

[5 rows x 22 columns]

In [4]:
fingers_dictionary = sorted(df[['f1', 'f2', 'f3']].melt()['value'].str.upper().unique())

In [54]:
fingers_dictionary

['AKRMLGQ---',
 'AKRMLGQHIRT',
 'AMGHLVEHIRT',
 'AREVLQRHTR',
 'AREVLQRHTRT',
 'ARSNLLRHTR',
 'ARSNLLRHTRT',
 'ASADLTR',
 'ASADLTRHIR',
 'ASDDLTQ',
 'ASSTRTK',
 'ASWELTRHIR',
 'ATGA-HN---',
 'CCAHLSEHIRT',
 'CPSNLRRHGRT',
 'CSDHLTTHIR',
 'DASARKRHTK',
 'DASTRKRHTK',
 'DCRDLAR---',
 'DCRDLARHIRT',
 'DHANLARHTR',
 'DHANLARHTRT',
 'DHQDLTIHIRT',
 'DHSSRKRHTK',
 'DKKDLTRHIRT',
 'DLRSCRSHIRT',
 'DLRWLVVHIRT',
 'DPGALVR---',
 'DPGALVRHIRT',
 'DPGDLVRHIRT',
 'DPGELVRHIRT',
 'DPGHLARHIRT',
 'DPGHLVRHIRT',
 'DPGKLARHIRT',
 'DPGNLKR---',
 'DPGNLKRHIRT',
 'DPGNLVRHIRT',
 'DPHNRKRHTK',
 'DRANLST',
 'DRANRKRHTK',
 'DRKVLATHIRT',
 'DRRLLDRHQR',
 'DRRLLDRHQRT',
 'DRSALARAHLRW',
 'DRSALARDHLSK',
 'DRSALARRHKRT',
 'DRSDLTRDHLSK',
 'DRSDLTRRHKRT',
 'DRSHLARDHLSK',
 'DRSHLARRHKRT',
 'DRSHLTRAHLRW',
 'DRSKLARHIRT',
 'DRSNLERHTR',
 'DRSNLERHTRT',
 'DRSNLTRAHLRW',
 'DRSNLTRDHLSK',
 'DRSNLTRRHKRT',
 'DRSSLTRHTR',
 'DRSSLTRHTRT',
 'DSAHLTR',
 'DSANLTRHIR',
 'DSANRTK',
 'DSGNLRVHIRT',
 'DSKDLTRHIR',
 'DSRARKRH

In [5]:
dna_dictionary = df['dna'].str.upper().unique()

In [53]:
dna_dictionary

array(['CTCGCGGGGGCGGCC', 'CTCGATTGGGCGGCC', 'CTCGATAAAGCGGCC',
       'CTCGATAACGCGGCC', 'CTCGATAAGGCGGCC', 'CTCGATAATGCGGCC',
       'CTCGATACAGCGGCC', 'CTCGATACCGCGGCC', 'CTCGATACGGCGGCC',
       'CTCGATACTGCGGCC', 'CTCGATAGAGCGGCC', 'CTCGATAGGGCGGCC',
       'CTCGATATAGCGGCC', 'CTCGATATGGCGGCC', 'CTCGATATTGCGGCC',
       'CTCGATAGTGCGGCC', 'CTCGATTAGGCGGCC', 'CTCGATCAAGCGGCC',
       'CTCGATCCAGCGGCC', 'CTCGATCGAGCGGCC', 'CTCGATCTAGCGGCC',
       'CTCGATCACGCGGCC', 'CTCGATCCCGCGGCC', 'CTCGATCGCGCGGCC',
       'CTCGATCTCGCGGCC', 'CTCGATCAGGCGGCC', 'CTCGATCCGGCGGCC',
       'CTCGATCGGGCGGCC', 'CTCGATCTGGCGGCC', 'CTCGATCATGCGGCC',
       'CTCGATCCTGCGGCC', 'CTCGATCGTGCGGCC', 'CTCGATCTTGCGGCC',
       'CCCGCGGGGGCGTCC', 'CCCGCGGGAGCGTCC', 'CCCGCGGGTGCGTCC',
       'CCCGCGGGCGCGTCC', 'CCCGCGGAGGCGTCC', 'CCCGCGGAAGCGTCC',
       'CCCGCGGATGCGTCC', 'CCCGCGGACGCGTCC', 'CCCGCGGTGGCGTCC',
       'CCCGCGGTAGCGTCC', 'CCCGCGGTTGCGTCC', 'CCCGCGGTCGCGTCC',
       'CCCGCGGCGGCGTCC', 'CCCGCGGCAGCGT

In [6]:
dna_data = df['dna'].str.upper().map(lambda x: list(dna_dictionary).index(x))

In [7]:
finger_data = np.array([df['f1'].str.upper().map(lambda x: list(fingers_dictionary).index(x)).values, 
 df['f2'].str.upper().map(lambda x: list(fingers_dictionary).index(x)).values,
 df['f3'].str.upper().map(lambda x: list(fingers_dictionary).index(x)).values])

In [8]:
dna_data.shape

(3099,)

In [9]:
finger_data.shape

(3, 3099)

In [10]:
dna_data[0:5]

0    0
1    0
2    0
3    0
4    0
Name: dna, dtype: int64

In [11]:
%matplotlib notebook

In [12]:
pd.DataFrame(dna_data).median()

dna    110.0
dtype: float64

In [13]:
finger_data[:, dna_data == 0]

array([[179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179],
       [689, 689, 689, 689, 689, 689, 689, 689, 689, 689, 689, 689],
       [653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653]])

In [14]:
np.unique(finger_data[:, dna_data == 34])

array([179, 273, 366, 417, 454, 653])

In [15]:
pd.Series(finger_data[:, dna_data == 34].ravel()).value_counts()

179    49
653    49
454    23
366    19
417     6
273     1
dtype: int64

In [16]:
finger_data[:, dna_data == 34]

array([[179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179],
       [366, 273, 366, 366, 366, 366, 366, 366, 366, 366, 366, 366, 454,
        417, 366, 454, 366, 366, 366, 454, 454, 454, 454, 454, 454, 454,
        454, 454, 454, 417, 417, 417, 417, 417, 366, 366, 366, 366, 454,
        454, 454, 454, 454, 454, 454, 454, 454, 454, 454],
       [653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653,
        653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653,
        653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653,
        653, 653, 653, 653, 653, 653, 653, 653, 653, 653]])

In [17]:
finger_data[:, dna_data == 35]

array([[179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179],
       [806, 828, 854, 898, 928, 926, 877, 880, 900, 902, 806, 806, 806,
        806, 806, 806, 806, 884, 884, 884, 884, 884, 884, 884, 884, 884,
        884, 884, 884, 884, 884, 884, 884, 884, 900, 902, 870, 884, 804,
        884, 884, 884, 884, 884, 884, 900, 900, 900, 900, 900, 900, 900,
        902, 902, 902, 902, 902, 870, 870, 870, 870, 870, 870, 870, 884,
        884, 884, 884, 884, 804, 804, 804, 804, 804, 804, 804, 804, 804],
       [653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653, 653,
        653, 653, 653, 653, 653, 653, 653, 653, 6

In [18]:
list(df['dna'].loc[dna_data[dna_data == 35].index].unique())

['cccgcgGGTgcgtcc']

In [19]:
list(df['dna'].loc[dna_data[dna_data == 34].index].unique())

['cccgcgGGAgcgtcc']

In [20]:
finger_data[:, dna_data == 36]

array([[179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179],
       [ 98,  98,  98,  98,  98,  98,  98,  98,  98,  98,  98,  32,  32,
         32,  32,  32,  32,  32,  32,  32,  32,  32,  32, 884,  32, 192,
         32,  98,  51,  33,  31, 367, 457, 886, 192, 192,  32,  32,  32,
         32,  32,  32,  32,  32,  32,  98,  98,  98,  51,  51,  51,  51,
         51,  51,  51,  51,  51,  33,  33,  33,  33,  33,  33,  31,  31,
         31,  31,  31,  31,  31,  31,  31,  31, 367, 367, 367, 367, 457,
        457, 457, 457, 457, 886],
       [653, 653, 653, 653, 653, 653, 653, 653, 653, 653

In [21]:
list(df['dna'].loc[dna_data[dna_data == 36].index].unique())

['cccgcgGGCgcgtcc']

In [22]:
list(df['dna'].loc[dna_data[dna_data == 37].index].unique())

['cccgcgGAGgcgtcc']

In [23]:
finger_data[:, dna_data == 37]

array([[179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179, 179,
        179, 179, 179, 179, 179, 179, 179],
       [706, 595, 522, 543, 628, 706, 706, 706, 706, 706, 706, 706, 706,
        706, 706, 706, 706, 706, 706, 711, 711, 711, 711, 711, 711, 711,
        711, 711, 647, 628, 706, 711, 620, 628, 716, 724, 615, 187, 190,
        191, 646, 613, 706, 706, 706, 706, 706, 706, 706, 706, 706, 706,
        706, 711, 711, 620, 620, 628, 716, 716, 716, 716, 724, 724, 724,
        724, 187, 187, 190, 190, 190, 190, 646, 646, 646, 646, 613, 613,
        613, 613, 613, 613, 613, 613, 613],
       [653, 653, 653, 653, 653, 653

In [24]:
list(df['dna2'].loc[dna_data[dna_data == 37].index].unique())

[nan,
 'cccgcgGGGgcgtcc',
 'cccgcgGGAgcgtcc',
 'cccgcgGGTgcgtcc',
 'cccgcgGGCgcgtcc',
 'cccgcgGAAgcgtcc',
 'cccgcgGATgcgtcc',
 'cccgcgGACgcgtcc',
 'cccgcgGTGgcgtcc',
 'cccgcgGTAgcgtcc',
 'cccgcgGTTgcgtcc',
 'cccgcgGTCgcgtcc',
 'cccgcgGCGgcgtcc',
 'cccgcgGCAgcgtcc',
 'cccgcgGCCgcgtcc',
 'cccgcgGCTgcgtcc']

In [25]:
list(df['dna'].loc[dna_data[dna_data == 37].index].unique())

['cccgcgGAGgcgtcc']

+ Look at f2 when dna > dna2: is it consistent 
+ Does the variation in f2 come from dna2 > dna - NO

In [36]:
finger_data[1, dna_data == 37]

array([706, 595, 522, 543, 628, 706, 706, 706, 706, 706, 706, 706, 706,
       706, 706, 706, 706, 706, 706, 711, 711, 711, 711, 711, 711, 711,
       711, 711, 647, 628, 706, 711, 620, 628, 716, 724, 615, 187, 190,
       191, 646, 613, 706, 706, 706, 706, 706, 706, 706, 706, 706, 706,
       706, 711, 711, 620, 620, 628, 716, 716, 716, 716, 724, 724, 724,
       724, 187, 187, 190, 190, 190, 190, 646, 646, 646, 646, 613, 613,
       613, 613, 613, 613, 613, 613, 613])

In [46]:
list(df['ex'].loc[dna_data[dna_data == 36]])

['+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+',
 '+']